use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'MyLocalServer_Example' do
  pod 'MyLocalServer', :path => '../'

  target 'MyLocalServer_Tests' do
    inherit! :search_paths

    
  end
end
